name: Build Templater Docker Images

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GO_VERSION: '1.20'


jobs:

  build-dockerfiles:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      - uses: actions/checkout@v3

      - name: Set up GO
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
        
      - name: Generate Dockerfiles
        run: | 
          go run main.go \
            -dockerfile.tpl pkg/docker/Dockerfile.tpl \
            -output.fmt "Dockerfile.{{ .image.name }}.{{ .image.tag }}" . \
            -variants pkg/docker/variants.yml.tpl \
            -variants.cfg pkg/docker/variants.cfg.yml

      - name: Upload Generated Dockerfiles
        uses: actions/upload-artifact@v3
        with:
          name: dockerfiles
          path: dockerfiles

  release-dockerimages:
    runs-on: ubuntu-latest

    needs: build-dockerfiles

    strategy:
      matrix:
        dockerfile: [Dockerfile.templater.debug, Dockerfile.templater.latest]

    permissions:
      contents: read
      packages: write

    steps:

      - uses: actions/checkout@v3

      - name: Download Generated Dockerfiles
        uses: actions/download-artifact@v3
        with:
          name: dockerfiles
          path: ${{ github.workspace }}/dockerfiles

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} 

      - name: Set Image Tag
        run: |
          echo "IMAGE_TAG=$(echo ${{ matrix.dockerfile }} | cut -d '.' -f 3)" >> $GITHUB_ENV
          ls -la ${{ github.workspace }}/dockerfiles

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ${{ github.workspace }}
          file: ${{ github.workspace }}/dockerfiles/${{ matrix.dockerfile }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}