name: Release

on:
  push:
    tags:
      - '*'
  workflow_run:
    workflows: ["Build Templater Docker Images"]
    types:
      - completed

jobs:
  release:

    if: |
      startsWith(github.event.ref, 'refs/tags/') &&
      github.event.workflow_run.conclusion == 'success'

    name: Release version
    runs-on: ubuntu-latest
    env:
      GO_VERSION: '1.20'
      CGO_ENABLED: 0

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # https://goreleaser.com/ci/actions/
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release -p 1 --clean --timeout=90m
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}